on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check Docker version
      run: docker version

    - name: Build and Start Docker Containers
      run: docker compose up -d --build

    - name: Wait for DB to be ready
      run: |
        until docker compose exec -T db pg_isready -U postgres; do
          echo "Waiting for db to be ready..."
          sleep 2
        done

    - name: Run Migrations
      run: docker compose exec web python manage.py migrate

    - name: Run Tests
      run: docker compose exec web python manage.py test

    - name: Shut down and Clean up
      run: docker compose down --volumes --remove-orphans

