# Generated by Django 5.1.1 on 2024-10-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trails',
            old_name='trailname',
            new_name='trailName',
        ),
    ]
