# Generated by Django 5.1.1 on 2024-10-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0002_rename_trailname_trails_trailname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trails',
        ),
    ]
