# Generated by Django 5.1.1 on 2024-10-26 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0003_delete_trails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailName', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('Front Range', 'Front Range'), ('San Juans', 'San Juans')], max_length=100)),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
