# Generated by Django 5.1.1 on 2024-10-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0005_alter_reports_approvalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='trailName',
            field=models.CharField(max_length=100),
        ),
    ]
