# Generated by Django 5.1.1 on 2024-10-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0006_alter_reports_trailname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(choices=[('Front Range', 'Front Range'), ('San Juans', 'San Juans'), ('Grand Mesa', 'Grand Mesa'), ('Grand Lake', 'Grand Lake'), ('Other', 'Other')], max_length=100),
        ),
    ]
