# Generated by Django 5.1.1 on 2024-10-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0009_alter_reports_trailname_alter_trails_trailname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='approvalStatus',
            field=models.BooleanField(default=True),
        ),
    ]
