# Generated by Django 5.1.1 on 2024-10-31 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0010_alter_reports_approvalstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='trailName',
        ),
        migrations.AddField(
            model_name='reports',
            name='trail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corduroyserver.trails'),
        ),
        migrations.AlterField(
            model_name='trails',
            name='trailName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
