# Generated by Django 5.1.1 on 2024-10-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0011_remove_reports_trailname_reports_trail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='approvalStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='report',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reports',
            name='trail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='corduroyserver.trails'),
        ),
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trails',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trails',
            name='trailName',
            field=models.CharField(max_length=100),
        ),
    ]
