# Generated by Django 5.1.1 on 2024-10-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corduroyserver', '0012_alter_reports_approvalstatus_alter_reports_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trails',
            name='location',
            field=models.CharField(choices=[('Front Range', 'Front Range'), ('San Juans', 'San Juans'), ('Grand Mesa', 'Grand Mesa'), ('Grand Lake', 'Grand Lake'), ('Other', 'Other')], max_length=100),
        ),
    ]
