#Gives annoying error
#version: '3.8'

services:
  corduroyserver:  # Django server with (corduroyserver)
    build: .
    ports:
      - "8000:8000"  # Expose Django app on port 8000
    volumes:
      - .:/app  # Mount the current directory for live reloading
    depends_on:
      - corduroydb  # Ensure the database is running before Django starts
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  # PostgreSQL Database
  # This makes use of the standard Postgres image, which uses the defautl PostgreSQL username and password and is not approriate for production
  corduroydb:
    image: postgres
    ports:
      - "5432:5432"  # Expose Postgres on port 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: corduroydb
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist Postgres data across restarts

volumes:
  db-data:  # Persistent volume for Postgres data
